import { describe, it, expect, afterEach } from 'vitest'
import { build } from 'vite'
import { readFileSync, rmSync } from 'node:fs'
import { resolve } from 'node:path'
import type { Json5Options } from '../src'
import json5Plugin from '../src'

const pkgRoot = resolve(__dirname, '..')
const testOutRel = 'node_modules/.vite-plugin-json5-test/types.d.ts'
const testOutAbs = resolve(pkgRoot, testOutRel)

afterEach(() => {
  rmSync(resolve(pkgRoot, 'node_modules/.vite-plugin-json5-test'), { recursive: true, force: true })
})

async function runBuild (dts: Json5Options['dts']): Promise<string> {
  await build({
    root: pkgRoot,
    plugins: [
      {
        name: 'virtual-entry',
        resolveId: (id) => id === 'entry' ? '\0entry' : null,
        load: (id) => id === '\0entry'
          ? `import '@fixtures/json5_example.json5'; import '@fixtures/jsonc_example.jsonc'`
          : null
      },
      json5Plugin({ dts })
    ],
    resolve: {
      alias: { '@fixtures': resolve(pkgRoot, 'tests/json') }
    },
    build: {
      write: false,
      rollupOptions: { input: 'entry' }
    },
    logLevel: 'silent'
  })
  return readFileSync(testOutAbs, 'utf-8')
}

describe('dts (aggregated mode)', () => {
  it('writes auto-generated header', async () => {
    const content = await runBuild({ outFile: testOutRel })
    expect(content).toMatch(/^\/\/ Auto-generated by vite-plugin-json5/)
  })

  it('generates a declare module block for each imported file', async () => {
    const content = await runBuild({ outFile: testOutRel })
    expect(content).toContain('declare module "@fixtures/json5_example.json5"')
    expect(content).toContain('declare module "@fixtures/jsonc_example.jsonc"')
  })

  it('includes named exports for top-level keys', async () => {
    const content = await runBuild({ outFile: testOutRel })
    expect(content).toContain('export declare const name:')
    expect(content).toContain('export declare const version:')
    expect(content).toContain('export declare const settings:')
  })

  it('includes a default export', async () => {
    const content = await runBuild({ outFile: testOutRel })
    expect(content).toContain('declare const _default:')
    expect(content).toContain('export default _default')
  })

  it('widens primitive types by default', async () => {
    const content = await runBuild({ outFile: testOutRel })
    expect(content).toContain('name: string')
    expect(content).toContain('version: string')
    expect(content).toContain('maxItems: number')
    expect(content).toContain('enabled: boolean')
  })

  it('uses literal types when literals: true', async () => {
    const content = await runBuild({ outFile: testOutRel, literals: true })
    expect(content).toContain('name: "Example JSON5"')
    expect(content).toContain('version: "1.0.0"')
    expect(content).toContain('maxItems: 100')
    expect(content).toContain('enabled: true')
  })

  it('does not write a file when dts is disabled', async () => {
    await build({
      root: pkgRoot,
      plugins: [
        {
          name: 'virtual-entry',
          resolveId: (id) => id === 'entry' ? '\0entry' : null,
          load: (id) => id === '\0entry' ? `import '@fixtures/json5_example.json5'` : null
        },
        json5Plugin({ dts: false })
      ],
      resolve: { alias: { '@fixtures': resolve(pkgRoot, 'tests/json') } },
      build: { write: false, rollupOptions: { input: 'entry' } },
      logLevel: 'silent'
    })
    expect(() => readFileSync(testOutAbs)).toThrow()
  })
})
