import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'

/** Options for aggregated DTS mode (default). */
export interface DtsAggregatedOptions {
  sidecar?: false
  literals?: boolean
  /** Output path relative to the Vite root. Defaults to `node_modules/@types/__vite-plugin-json5__/index.d.ts`. */
  outFile?: string
}

/** Options for sidecar DTS mode. `outFile` is not available in this mode. */
export interface DtsSidecarOptions {
  sidecar: true
  literals?: boolean
}

const identRE = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/

function inferTsType(value: unknown, literals = false): string {
  if (value === null) return 'null'
  if (Array.isArray(value)) {
    if (value.length === 0) return 'unknown[]'
    if (literals) return `[${value.map(v => inferTsType(v, true)).join(', ')}]`
    const types = [...new Set(value.map(v => inferTsType(v)))]
    return `Array<${types.join(' | ')}>`
  }
  if (typeof value === 'object') {
    const props = Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${identRE.test(k) ? k : JSON.stringify(k)}: ${inferTsType(v, literals)}`)
      .join(', ')
    return `{ ${props} }`
  }
  if (typeof value === 'string') return literals ? JSON.stringify(value) : 'string'
  if (typeof value === 'number') return literals ? String(value) : 'number'
  if (typeof value === 'boolean') return literals ? String(value) : 'boolean'
  return 'unknown'
}

export function generateModuleBlock(specifier: string, parsed: unknown, namedExports: boolean, literals: boolean): string {
  const lines: string[] = [`declare module ${JSON.stringify(specifier)} {`]

  if (namedExports && parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed)) {
    for (const [key, value] of Object.entries(parsed as Record<string, unknown>)) {
      if (identRE.test(key)) {
        lines.push(`  export declare const ${key}: ${inferTsType(value, literals)}`)
      }
    }
    lines.push('')
  }

  lines.push(`  declare const _default: ${inferTsType(parsed, literals)}`)
  lines.push('  export default _default')
  lines.push('}')

  return lines.join('\n')
}

export function generateSidecarContent(parsed: unknown, namedExports: boolean, literals: boolean): string {
  const lines: string[] = ['// Auto-generated by vite-plugin-json5 — do not edit', '']
  if (namedExports && parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed)) {
    for (const [key, value] of Object.entries(parsed as Record<string, unknown>)) {
      if (identRE.test(key)) {
        lines.push(`export declare const ${key}: ${inferTsType(value, literals)}`)
      }
    }
    lines.push('')
  }
  lines.push(`declare const _default: ${inferTsType(parsed, literals)}`)
  lines.push('export default _default')
  return lines.join('\n') + '\n'
}

export function writeDtsFile(outFile: string, declarations: Map<string, string>): void {
  const content = [
    '// Auto-generated by vite-plugin-json5 — do not edit',
    '',
    ...declarations.values(),
  ].join('\n\n') + '\n'
  mkdirSync(dirname(outFile), { recursive: true })
  writeFileSync(outFile, content, 'utf-8')
}
