import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import JSON5 from 'json5'
import type { Plugin, JsonOptions } from 'vite'
import { dataToEsm } from '@rollup/pluginutils'

const json5ExtRE = /\.(jsonc|json5)$/
const identRE = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/

/** Options for aggregated DTS mode (default). */
export type DtsAggregatedOptions = {
  sidecar?: false
  literals?: boolean
  /** Output path relative to the Vite root. Defaults to `node_modules/.vite-plugin-json5/types.d.ts`. */
  outFile?: string
}

/** Options for sidecar DTS mode. `outFile` is not available in this mode. */
export type DtsSidecarOptions = {
  sidecar: true
  literals?: boolean
}

export interface Json5Options extends JsonOptions {
  /**
   * Automatically generate TypeScript declarations for imported JSON5/JSONC
   * files, inferred from each file's contents.
   *
   * Pass `true` to enable with defaults, or an options object to choose a mode:
   *
   * - **Aggregated** (default) — all declarations go into a single file
   *   (`node_modules/.vite-plugin-json5/types.d.ts`). Add it to `files` in
   *   your `tsconfig.json` to activate:
   *   ```json
   *   { "files": ["node_modules/.vite-plugin-json5/types.d.ts"] }
   *   ```
   * - **Sidecar** (`sidecar: true`) — writes a `.d.ts` next to each source
   *   file; TypeScript picks it up automatically, no tsconfig change needed.
   *   Add `*.json5.d.ts` / `*.jsonc.d.ts` to your `.gitignore`.
   *
   * Set `literals: true` on either mode to use exact literal types instead
   * of widened primitives (e.g. `"1.0.0"` instead of `string`).
   */
  dts?: boolean | DtsAggregatedOptions | DtsSidecarOptions
}

function inferTsType (value: unknown, literals = false): string {
  if (value === null) return 'null'
  if (Array.isArray(value)) {
    if (value.length === 0) return 'unknown[]'
    if (literals) return `[${value.map(v => inferTsType(v, true)).join(', ')}]`
    const types = [...new Set(value.map(v => inferTsType(v)))]
    return `Array<${types.join(' | ')}>`
  }
  if (typeof value === 'object') {
    const props = Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${identRE.test(k) ? k : JSON.stringify(k)}: ${inferTsType(v, literals)}`)
      .join(', ')
    return `{ ${props} }`
  }
  if (typeof value === 'string') return literals ? JSON.stringify(value) : 'string'
  if (typeof value === 'number') return literals ? String(value) : 'number'
  if (typeof value === 'boolean') return literals ? String(value) : 'boolean'
  return 'unknown'
}

function generateModuleBlock (specifier: string, parsed: unknown, namedExports: boolean, literals: boolean): string {
  const lines: string[] = [`declare module ${JSON.stringify(specifier)} {`]

  if (namedExports && parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed)) {
    for (const [key, value] of Object.entries(parsed as Record<string, unknown>)) {
      if (identRE.test(key)) {
        lines.push(`  export declare const ${key}: ${inferTsType(value, literals)}`)
      }
    }
    lines.push('')
  }

  lines.push(`  declare const _default: ${inferTsType(parsed, literals)}`)
  lines.push('  export default _default')
  lines.push('}')

  return lines.join('\n')
}

function generateSidecarContent (parsed: unknown, namedExports: boolean, literals: boolean): string {
  const lines: string[] = ['// Auto-generated by vite-plugin-json5 — do not edit', '']
  if (namedExports && parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed)) {
    for (const [key, value] of Object.entries(parsed as Record<string, unknown>)) {
      if (identRE.test(key)) {
        lines.push(`export declare const ${key}: ${inferTsType(value, literals)}`)
      }
    }
    lines.push('')
  }
  lines.push(`declare const _default: ${inferTsType(parsed, literals)}`)
  lines.push('export default _default')
  return lines.join('\n') + '\n'
}

function writeDtsFile (outFile: string, declarations: Map<string, string>): void {
  const content = [
    '// Auto-generated by vite-plugin-json5 — do not edit',
    '',
    ...declarations.values()
  ].join('\n\n') + '\n'
  mkdirSync(dirname(outFile), { recursive: true })
  writeFileSync(outFile, content, 'utf-8')
}

export function json5Plugin (
  options: Json5Options = {}
): Plugin {
  const dtsOpts: DtsAggregatedOptions | DtsSidecarOptions | null = options.dts
    ? (typeof options.dts === 'object' ? options.dts : {})
    : null
  const dtsLiterals = dtsOpts?.literals === true
  const dtsSidecar = dtsOpts?.sidecar === true

  let isBuild = false
  let dtsOutFile: string | null = null
  const specifiersFor = new Map<string, Set<string>>()
  const declarations = new Map<string, string>()

  return {
    name: 'vite:json5',

    configResolved (config) {
      isBuild = config.command === 'build'
      if (dtsOpts !== null && dtsOpts.sidecar !== true) {
        const outFile = dtsOpts.outFile ?? 'node_modules/.vite-plugin-json5/types.d.ts'
        dtsOutFile = resolve(config.root, outFile)
      }
    },

    ...(dtsOpts !== null && !dtsSidecar && {
      resolveId: {
        order: 'pre' as const,
        async handler (id: string, importer: string | undefined) {
          if (!json5ExtRE.test(id.split('?')[0])) return null
          // Skip absolute/filesystem paths — only capture user-written specifiers
          if (id.startsWith('/') || /^[A-Za-z]:[/\\]/.test(id)) return null
          const resolved = await this.resolve(id, importer, { skipSelf: true })
          if (resolved && !resolved.external) {
            const set = specifiersFor.get(resolved.id) ?? new Set<string>()
            set.add(id)
            specifiersFor.set(resolved.id, set)
          }
          return null
        }
      }
    }),

    transform (json, id) {
      if (!json5ExtRE.test(id)) return null

      try {
        const parsed = JSON5.parse(json)

        if (dtsOpts !== null) {
          const namedExports = options.namedExports !== false && options.stringify !== true
          if (dtsSidecar) {
            writeFileSync(`${id}.d.ts`, generateSidecarContent(parsed, namedExports, dtsLiterals), 'utf-8')
          } else if (dtsOutFile !== null) {
            for (const specifier of specifiersFor.get(id) ?? []) {
              declarations.set(specifier, generateModuleBlock(specifier, parsed, namedExports, dtsLiterals))
            }
            if (specifiersFor.has(id)) {
              writeDtsFile(dtsOutFile, declarations)
            }
          }
        }

        if (options.stringify === true) {
          json = JSON.stringify(parsed)

          if (isBuild) {
            return {
              code: `export default JSON.parse(${JSON.stringify(json)})`,
              map: { mappings: '' }
            }
          } else {
            return {
              code: `export default JSON.parse(${JSON.stringify(json)})`,
              map: null
            }
          }
        }

        return {
          code: dataToEsm(parsed, {
            namedExports: options.namedExports
          }),
          map: { mappings: '' }
        }
      } catch (e) {
        const error = e instanceof Error ? e : new Error(String(e))
        this.error(error.message)
      }
    }
  }
}

export default json5Plugin
